# Generated by Django 4.2.29 on 2026-03-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Минимальное количество')),
                ('notify', models.BooleanField(default=True, verbose_name='Уведомлять о нехватке')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='min_stock_level', to='products.product')),
            ],
            options={
                'verbose_name': 'Минимальный остаток',
                'verbose_name_plural': 'Минимальные остатки',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='warehouse.cell')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='products.product')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'ordering': ['product', 'cell'],
                'unique_together': {('product', 'cell')},
            },
        ),
    ]
