# Generated by Django 5.2.12 on 2026-03-21 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_audit_fields'),
        ('products', '0004_add_units_table'),
        ('warehouse', '0002_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На согласовании'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('issued', 'Выдана')], db_index=True, default='draft', max_length=20)),
                ('object_name', models.CharField(max_length=255, verbose_name='Объект')),
                ('work_type', models.CharField(blank=True, max_length=255, verbose_name='Вид работ')),
                ('needed_at', models.DateField(blank=True, null=True, verbose_name='Нужно к дате')),
                ('comment', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто одобрил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Заявка на материалы',
                'verbose_name_plural': 'Заявки на материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер накладной')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_notes', to='orders.materialrequest')),
            ],
            options={
                'verbose_name': 'Накладная выдачи',
                'verbose_name_plural': 'Накладные выдачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Выдано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_request_items', to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.materialrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Строка заявки',
                'verbose_name_plural': 'Строки заявки',
            },
        ),
        migrations.CreateModel(
            name='IssueNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_note_items', to='warehouse.cell')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('issue_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.issuenote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_note_items', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_note_items', to='orders.materialrequestitem')),
            ],
            options={
                'verbose_name': 'Строка накладной',
                'verbose_name_plural': 'Строки накладной',
            },
        ),
    ]
