# Generated by Django 5.2.12 on 2026-03-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('orders', '0004_materialrequest_issuenote_materialrequestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='construction.constructionobject', verbose_name='Строительный объект'),
        ),
    ]
