# Generated by Django 5.2.12 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_backfill_construction_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Объект'),
        ),
    ]
