# Generated by Django 5.2.12 on 2026-03-21 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('orders', '0007_alter_materialrequest_object_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issue_notes', to=settings.AUTH_USER_MODEL, verbose_name='Кто одобрил'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_notes', to='construction.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='status',
            field=models.CharField(choices=[('submitted', 'На согласовании'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_notes', to='orders.materialrequest'),
        ),
        migrations.AlterField(
            model_name='issuenoteitem',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_note_items', to='orders.materialrequestitem'),
        ),
    ]
