# Generated by Django 5.2.12 on 2026-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_issuenote_approved_at_issuenote_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenoteitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
