# Generated by Django 5.2.12 on 2026-03-22 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_issuenote_workflow_and_item_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenote',
            name='inspection_invited_users',
            field=models.ManyToManyField(blank=True, related_name='issue_notes_assigned_inspection', to=settings.AUTH_USER_MODEL, verbose_name='Контролёры на приёмку'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма закупки'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_counterparty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_delivery_notes',
            field=models.TextField(blank=True, verbose_name='Как везут, маршрут и т.д.'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закупки'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_quantity_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество (комментарий)'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_scan',
            field=models.FileField(blank=True, null=True, upload_to='procurement_scans/%Y/%m/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_vehicle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Транспорт / машина'),
        ),
        migrations.AddField(
            model_name='issuenoteitem',
            name='inspection_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий при приёмке'),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='status',
            field=models.CharField(choices=[('submitted', 'На согласовании'), ('awaiting_procurement', 'У снабжения'), ('procurement_active', 'Закупка'), ('await_ctrl_pick', 'Товар прибыл — назначить контролёра'), ('awaiting_controller', 'Ожидает приёмку'), ('awaiting_release', 'Ожидает выдачу со склада'), ('approved', 'Одобрена'), ('picking', 'Собирается'), ('ready_pickup', 'Готов к выдаче'), ('received_foreman', 'Прораб получил'), ('rejected', 'Отклонена')], db_index=True, default='submitted', max_length=24),
        ),
    ]
