# Generated by Django 5.2.12 on 2026-03-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_issuenote_inspection_invited_users_and_more'),
        ('receipts', '0003_add_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenote',
            name='procurement_item_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Позиции накладной под закупку (id строк)'),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='procurement_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_notes', to='receipts.supplier', verbose_name='Поставщик из справочника'),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='procurement_counterparty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контрагент (текст)'),
        ),
    ]
