# Generated by Django 5.2.12 on 2026-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_issuenote_procurement_supplier_and_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuenote',
            name='status',
            field=models.CharField(choices=[('submitted', 'На согласовании'), ('awaiting_procurement', 'У снабжения'), ('procurement_active', 'Закупка'), ('await_ctrl_pick', 'Товар прибыл — назначить контролёра'), ('awaiting_controller', 'Ожидает приёмку'), ('awaiting_release', 'Ожидает выдачу со склада'), ('warehouse_received', 'Товар принят на склад (накладная закрыта)'), ('approved', 'Одобрена'), ('picking', 'Собирается'), ('ready_pickup', 'Готов к выдаче'), ('received_foreman', 'Прораб получил'), ('rejected', 'Отклонена')], db_index=True, default='submitted', max_length=24),
        ),
    ]
