# Generated by Django 5.2.12 on 2026-03-22 17:48

from django.db import migrations, models


def forwards_note_completed(apps, schema_editor):
    IssueNote = apps.get_model("orders", "IssueNote")
    IssueNote.objects.filter(status="rejected").update(status="note_completed")
    IssueNote.objects.filter(status="received_foreman").update(status="note_completed")


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_warehouse_received_and_notifications'),
    ]

    operations = [
        migrations.RunPython(forwards_note_completed, backwards_noop),
        migrations.AlterField(
            model_name='issuenote',
            name='status',
            field=models.CharField(choices=[('submitted', 'На согласовании'), ('awaiting_procurement', 'У снабжения'), ('procurement_active', 'Закупка'), ('await_ctrl_pick', 'Товар прибыл — назначить контролёра'), ('awaiting_controller', 'Ожидает приёмку'), ('awaiting_release', 'Ожидает выдачу со склада'), ('warehouse_received', 'Товар принят на склад (накладная закрыта)'), ('approved', 'Одобрена'), ('picking', 'Собирается'), ('ready_pickup', 'Готов к выдаче'), ('note_completed', 'Завершена')], db_index=True, default='submitted', max_length=24),
        ),
    ]
