# Generated by Django 5.2.12 on 2026-03-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_note_completed_status'),
        ('products', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenoteitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_note_items', to='products.service'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_request_items', to='products.service'),
        ),
        migrations.AlterField(
            model_name='issuenoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_note_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_request_items', to='products.product'),
        ),
    ]
