# Generated by Django 5.2.12 on 2026-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Фото'),
        ),
    ]
