# Generated by Django 5.2.12 on 2026-03-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_units_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код')),
                ('unit', models.CharField(default='усл.', max_length=20, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
    ]
