# Generated by Django 5.2.12 on 2026-03-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_default_object_type(apps, schema_editor):
    ConstructionObject = apps.get_model("construction", "ConstructionObject")
    ConstructionObjectType = apps.get_model("construction", "ConstructionObjectType")
    default_type, _ = ConstructionObjectType.objects.get_or_create(
        name="Общий тип",
        defaults={"code": "default", "description": "Автосозданный тип для ранее существующих объектов", "is_active": True},
    )
    ConstructionObject.objects.filter(object_type__isnull=True).update(object_type=default_type)


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('products', '0005_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='limit_amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Лимит суммы (override)'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='limit_quantity_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Лимит количества (override)'),
        ),
        migrations.CreateModel(
            name='ConstructionObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип объекта')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Код типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('limit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Лимит суммы')),
                ('limit_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Лимит количества')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('allowed_products', models.ManyToManyField(blank=True, related_name='allowed_in_object_types', to='products.product', verbose_name='Разрешенные товары')),
                ('allowed_services', models.ManyToManyField(blank=True, related_name='allowed_in_object_types', to='products.service', verbose_name='Разрешенные услуги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Тип строительного объекта',
                'verbose_name_plural': 'Типы строительных объектов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_objects', to='construction.constructionobjecttype', verbose_name='Тип объекта'),
        ),
        migrations.RunPython(backfill_default_object_type, migrations.RunPython.noop),
    ]
