# Generated by Django 5.2.12 on 2026-03-31 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_constructionobject_limit_amount_override_and_more'),
        ('products', '0005_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObjectTypeItemLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('limit_quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Лимит количества')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_limits', to='construction.constructionobjecttype', verbose_name='Тип объекта')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_type_limits', to='products.product', verbose_name='Товар')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_type_limits', to='products.service', verbose_name='Услуга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Лимит типа объекта по позиции',
                'verbose_name_plural': 'Лимиты типов объектов по позициям',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='construction_type_limit_exactly_one_item'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('object_type', 'product'), name='construction_type_limit_unique_product'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('object_type', 'service'), name='construction_type_limit_unique_service')],
            },
        ),
    ]
