# Generated by Django 5.2.12 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('storekeeper', 'Кладовщик'), ('foreman', 'Прораб')], max_length=20, unique=True),
        ),
    ]
