# Generated by Django 5.2.12 on 2026-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_objects',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='construction.constructionobject', verbose_name='Закрепленные объекты'),
        ),
    ]
