# Generated by Django 5.2.12 on 2026-03-21 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_assigned_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePolicyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('state', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Состояние')),
                ('role_name', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('storekeeper', 'Кладовщик'), ('foreman', 'Прораб')], db_index=True, max_length=20)),
                ('resource', models.CharField(db_index=True, max_length=64)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Переопределение прав роли',
                'verbose_name_plural': 'Переопределения прав ролей',
                'unique_together': {('role_name', 'resource')},
            },
        ),
    ]
