# Generated by Django 5.2.12 on 2026-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rolepolicyoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rolepolicyoverride',
            name='role_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
