# Generated by Django 5.2.12 on 2026-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_name_alter_rolepolicyoverride_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='device',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='page',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
